services:
  postgres:
    image: postgres
    container_name: test_prisma_postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-test_prisma}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-abc123}
    ports:
      - "5432:5432"
    restart: on-failure